% --- 1. Extract Data ---
east = out.EastPos.Data;
north = out.NorthPos.Data;

% --- 2. Define Beacon Coordinates (North, East) ---
% Format: [North, East]
beacons = [
    15000, 15000;   % VOR 1
    0,     30000;   % VOR 2
   -15000, 30000;   % VOR 3
   -30000, 45000;   % VOR 4
    0,     0        % VOR 5 (Home)
];

% --- 3. Create Plot ---
figure('Color', 'w'); % White background for reports
hold on; grid on; box on;

% Plot the Capture Circles (5000m radius)
theta = linspace(0, 2*pi, 100);
for i = 1:size(beacons, 1)
    fill(beacons(i,2) + 5000*cos(theta), ...
         beacons(i,1) + 5000*sin(theta), ...
         [0.9 0.9 0.9], ...
         'EdgeColor', [0.7 0.7 0.7], ...
         'LineStyle', '--', ...
         'FaceAlpha', 0.3);
end

% Plot the Aircraft Track
plot(east, north, ...
     'Color', [0 0.447 0.741], ...
     'LineWidth', 2, ...
     'DisplayName', 'Flight Path');

% Plot the VOR Stations
plot(beacons(:,2), beacons(:,1), ...
     'r^', ...
     'MarkerSize', 8, ...
     'MarkerFaceColor', 'r', ...
     'DisplayName', 'VOR Beacons');

% Mark Start and End Points
plot(east(1), north(1), ...
     'go', ...
     'MarkerSize', 10, ...
     'MarkerFaceColor', 'g', ...
     'DisplayName', 'Start');

plot(east(end), north(end), ...
     'rx', ...
     'MarkerSize', 12, ...
     'LineWidth', 2, ...
     'DisplayName', 'End');

% --- 4. Aesthetics ---
axis equal; % CRITICAL: Ensures circles look like circles
xlabel('East Position (m)', 'FontSize', 11, 'Color', 'k');
ylabel('North Position (m)', 'FontSize', 11, 'Color', 'k');
title('F-16 Navigational Performance: Horizontal Ground Track', ...
      'FontSize', 13, 'Color', 'k');
legend('Location', 'northeastoutside');

% Adjust axes slightly so circles aren't cut off
margin = 10000;
axis([min(east)-margin max(east)+margin ...
      min(north)-margin max(north)+margin]);

% Force axis tick marks and tick labels to black
ax = gca;
ax.XColor = 'k';
ax.YColor = 'k';
